apiVersion: v1
kind: Secret
metadata:
  name: opentoggl-secrets
  namespace: opentoggl-local
type: Opaque
stringData:
  postgres-password: change-me-please
  redis-password: change-me-please
  database-url: postgres://postgres:change-me-please@postgres:5432/opentoggl?sslmode=disable
  redis-url: redis://:change-me-please@redis:6379/0
